// Predefined word pairs for each category
// Format: { villager: "word", spy: "similar_word" }

const wordPairs = {
  food: [
    { villager: 'Grass', spy: 'Grassland' },
    { villager: 'Apple', spy: 'Pineapple' },
    { villager: 'Bread', spy: 'Toast' },
    { villager: 'Rice', spy: 'Risotto' },
    { villager: 'Chicken', spy: 'Turkey' },
    { villager: 'Pizza', spy: 'Calzone' },
    { villager: 'Pasta', spy: 'Spaghetti' },
    { villager: 'Salad', spy: 'Coleslaw' },
    { villager: 'Soup', spy: 'Stew' },
    { villager: 'Cake', spy: 'Cupcake' },
    { villager: 'Ice Cream', spy: 'Frozen Yogurt' },
    { villager: 'Burger', spy: 'Sandwich' },
    { villager: 'Sushi', spy: 'Sashimi' },
    { villager: 'Coffee', spy: 'Espresso' },
    { villager: 'Tea', spy: 'Herbal Tea' },
  ],

  animals: [
    { villager: 'Dog', spy: 'Wolf' },
    { villager: 'Cat', spy: 'Tiger' },
    { villager: 'Lion', spy: 'Tiger' },
    { villager: 'Elephant', spy: 'Mammoth' },
    { villager: 'Bird', spy: 'Eagle' },
    { villager: 'Fish', spy: 'Shark' },
    { villager: 'Horse', spy: 'Zebra' },
    { villager: 'Bear', spy: 'Panda' },
    { villager: 'Rabbit', spy: 'Hare' },
    { villager: 'Duck', spy: 'Goose' },
    { villager: 'Pig', spy: 'Boar' },
    { villager: 'Cow', spy: 'Bull' },
    { villager: 'Sheep', spy: 'Goat' },
    { villager: 'Monkey', spy: 'Ape' },
    { villager: 'Snake', spy: 'Serpent' },
  ],

  places: [
    { villager: 'Beach', spy: 'Shore' },
    { villager: 'Mountain', spy: 'Hill' },
    { villager: 'Forest', spy: 'Jungle' },
    { villager: 'Desert', spy: 'Oasis' },
    { villager: 'City', spy: 'Metropolis' },
    { villager: 'Village', spy: 'Town' },
    { villager: 'Island', spy: 'Peninsula' },
    { villager: 'River', spy: 'Stream' },
    { villager: 'Lake', spy: 'Pond' },
    { villager: 'Park', spy: 'Garden' },
    { villager: 'School', spy: 'University' },
    { villager: 'Hospital', spy: 'Clinic' },
    { villager: 'Restaurant', spy: 'Café' },
    { villager: 'Library', spy: 'Bookstore' },
    { villager: 'Airport', spy: 'Terminal' },
  ],

  movies: [
    { villager: 'Titanic', spy: 'Avatar' },
    { villager: 'Star Wars', spy: 'Star Trek' },
    { villager: 'Batman', spy: 'Superman' },
    { villager: 'Harry Potter', spy: 'Lord of the Rings' },
    { villager: 'Iron Man', spy: 'Iron Man 2' },
    { villager: 'Frozen', spy: 'Tangled' },
    { villager: 'Toy Story', spy: 'Cars' },
    { villager: 'Shrek', spy: 'Monsters Inc' },
    { villager: 'Finding Nemo', spy: 'Finding Dory' },
    { villager: 'The Matrix', spy: 'Inception' },
    { villager: 'Jurassic Park', spy: 'Jurassic World' },
    { villager: 'Spider-Man', spy: 'Spider-Man 2' },
    { villager: 'The Lion King', spy: 'The Jungle Book' },
    { villager: 'Aladdin', spy: 'Moana' },
    { villager: 'Frozen', spy: 'Frozen 2' },
  ],

  jobs: [
    { villager: 'Doctor', spy: 'Surgeon' },
    { villager: 'Teacher', spy: 'Professor' },
    { villager: 'Chef', spy: 'Cook' },
    { villager: 'Engineer', spy: 'Architect' },
    { villager: 'Artist', spy: 'Painter' },
    { villager: 'Writer', spy: 'Author' },
    { villager: 'Musician', spy: 'Composer' },
    { villager: 'Actor', spy: 'Actress' },
    { villager: 'Pilot', spy: 'Captain' },
    { villager: 'Lawyer', spy: 'Judge' },
    { villager: 'Nurse', spy: 'Doctor' },
    { villager: 'Police', spy: 'Detective' },
    { villager: 'Firefighter', spy: 'Paramedic' },
    { villager: 'Scientist', spy: 'Researcher' },
    { villager: 'Designer', spy: 'Stylist' },
  ],

  sports: [
    { villager: 'Football', spy: 'Soccer' },
    { villager: 'Basketball', spy: 'Volleyball' },
    { villager: 'Tennis', spy: 'Badminton' },
    { villager: 'Baseball', spy: 'Softball' },
    { villager: 'Swimming', spy: 'Diving' },
    { villager: 'Running', spy: 'Marathon' },
    { villager: 'Cycling', spy: 'Motorcycling' },
    { villager: 'Golf', spy: 'Mini Golf' },
    { villager: 'Boxing', spy: 'Wrestling' },
    { villager: 'Skiing', spy: 'Snowboarding' },
    { villager: 'Surfing', spy: 'Skateboarding' },
    { villager: 'Cricket', spy: 'Baseball' },
    { villager: 'Rugby', spy: 'American Football' },
    { villager: 'Hockey', spy: 'Ice Hockey' },
    { villager: 'Gymnastics', spy: 'Acrobatics' },
  ],

  countries: [
    { villager: 'USA', spy: 'Canada' },
    { villager: 'France', spy: 'Belgium' },
    { villager: 'Germany', spy: 'Austria' },
    { villager: 'Italy', spy: 'Spain' },
    { villager: 'Japan', spy: 'China' },
    { villager: 'India', spy: 'Pakistan' },
    { villager: 'Brazil', spy: 'Argentina' },
    { villager: 'Russia', spy: 'Ukraine' },
    { villager: 'Australia', spy: 'New Zealand' },
    { villager: 'UK', spy: 'Ireland' },
    { villager: 'Mexico', spy: 'Guatemala' },
    { villager: 'Egypt', spy: 'Morocco' },
    { villager: 'Greece', spy: 'Turkey' },
    { villager: 'Sweden', spy: 'Norway' },
    { villager: 'South Korea', spy: 'North Korea' },
  ],

  objects: [
    { villager: 'Phone', spy: 'Smartphone' },
    { villager: 'Computer', spy: 'Laptop' },
    { villager: 'Car', spy: 'Truck' },
    { villager: 'Bike', spy: 'Motorcycle' },
    { villager: 'Book', spy: 'Magazine' },
    { villager: 'Pen', spy: 'Pencil' },
    { villager: 'Table', spy: 'Desk' },
    { villager: 'Chair', spy: 'Stool' },
    { villager: 'Lamp', spy: 'Lantern' },
    { villager: 'Clock', spy: 'Watch' },
    { villager: 'Camera', spy: 'Video Camera' },
    { villager: 'Guitar', spy: 'Violin' },
    { villager: 'Ball', spy: 'Sphere' },
    { villager: 'Box', spy: 'Container' },
    { villager: 'Key', spy: 'Lock' },
  ],
};

module.exports = { wordPairs };

